import BarD3 from "./HorizontalChart";

export default {
  title: "HorizontalChart",
  component: BarD3,
  argTypes: {
    labelPosition: {
      type: "string",
      description: "Положение подписей",
      defaultValue: "end",
      options: ["end", "middle", "start", "none"],
      control: {
        type: "radio",
      },
    },
    height: {
      type: Number,
      description: "Высота чарта",
      control: { type: "range", min: 200, max: 1500, step: 50 },
    },
    visualMode: {
      type: "string",
      description: "Вид графика",
      defaultValue: "horizontal",
      options: ["horizontal", "vertical"],
      control: {
        type: "radio",
      },
    },
  },
};

const Template = (arg) => <BarD3 {...arg}></BarD3>;

export const HorizontalChart = Template.bind({});
HorizontalChart.args = {
  height: 700,
  width: 1000,
  labelFontSize: 20,
  yAxisFontSize: 14,
  xAxisFontSize: 14,
  xLimitLine: 100,
  paddingRight: 40,
  paddingLeft: 40,
  paddingTop: 0,
  paddingBottom: 40,
  legendX: 600,
  legendY: 5,
  labelPosition: "end",
  paddingForChart: "0 0 0 0",
  visualMode: "horizontal",
  cols: ["platform"],
  metrics: ["count"],
  data: [
    { platform: "TG16", count: 2 },
    { platform: "PSP", count: 1213 },
    { platform: "2600", count: 133 },
    { platform: "PS4", count: 336 },
    { platform: "N64", count: 319 },
    { platform: "GBA", count: 822 },
    { platform: "GG", count: 1 },
    { platform: "PSV", count: 411 },
    { platform: "XB", count: 824 },
    { platform: "DC", count: 52 },
    { platform: "XOne", count: 213 },
    { platform: "PS2", count: 2161 },
    { platform: "Wii", count: 1325 },
    { platform: "X360", count: 1265 },
    { platform: "WiiU", count: 143 },
    { platform: "PC", count: 960 },
    { platform: "DS", count: 2162 },
    { platform: "WS", count: 6 },
    { platform: "PCFX", count: 1 },
    { platform: "PS3", count: 1329 },
    { platform: "GEN", count: 27 },
    { platform: "SNES", count: 239 },
    { platform: "NG", count: 12 },
    { platform: "GB", count: 98 },
    { platform: "PS", count: 1196 },
    { platform: "SCD", count: 6 },
    { platform: "3DS", count: 509 },
    { platform: "3DO", count: 3 },
    { platform: "NES", count: 98 },
    { platform: "SAT", count: 173 },
    { platform: "GC", count: 556 },
  ],
};

const TemplateGroupedMode = (arg) => <BarD3 {...arg}></BarD3>;

export const HorizontalChart_GroupedMode = TemplateGroupedMode.bind({});
HorizontalChart_GroupedMode.args = {
  height: 700,
  width: 1000,
  labelFontSize: 20,
  yAxisFontSize: 14,
  xAxisFontSize: 14,
  xLimitLine: 100,
  paddingRight: 40,
  paddingLeft: 40,
  paddingTop: 0,
  paddingBottom: 40,
  legendX: 600,
  legendY: 5,
  labelPosition: "end",
  paddingInfoLabel: 10,
  visualMode: "horizontal",
  cols: ["year", "platform"],
  metrics: ["count"],
  data: [
    { year: 2011, platform: "PC", count: 140 },
    { year: 2008, platform: "PC", count: 76 },
    { year: 1992, platform: "NES", count: 3 },
    //{ year: 2009, platform: "PS2", count: 96 },
    { year: 1993, platform: "SCD", count: 1 },
    { year: 2006, platform: "PS2", count: 259 },
    //{ year: 1999, platform: "DC", count: 14 },
    { year: 2014, platform: "PSP", count: 10 },
    //{ year: 1992, platform: "GEN", count: 6 },
    //{ year: 1987, platform: "2600", count: 6 },
    //{ year: 1989, platform: "2600", count: 2 },
    //{ year: 2001, platform: "WS", count: 2 },
    //{ year: 1985, platform: "NES", count: 11 },
    //{ year: 2013, platform: "DS", count: 9 },
    { year: 2011, platform: "PS2", count: 7 },
    //{ year: 1999, platform: "N64", count: 102 },
    { year: 2006, platform: "X360", count: 93 },
    //{ year: 1997, platform: "SAT", count: 34 },
    { year: 2014, platform: "Wii", count: 6 },
    { year: 2008, platform: "Wii", count: 282 },
    { year: 2006, platform: "DS", count: 202 },
    //{ year: 2005, platform: "PSP", count: 97 },
    //{ year: 1998, platform: "PS", count: 248 },
    //{ year: 2016, platform: "3DS", count: 35 },
    //{ year: 2013, platform: "WiiU", count: 42 },
    { year: 2011, platform: "DS", count: 153 },
    //{ year: 2007, platform: "PS3", count: 90 },
    //{ year: 2015, platform: "PC", count: 50 },
    //{ year: 1994, platform: "NES", count: 1 },
    //{ year: 1991, platform: "SNES", count: 24 },
    //{ year: 2012, platform: "PC", count: 61 },
    //{ year: 1995, platform: "SNES", count: 54 },
    { year: 2006, platform: "PSP", count: 190 },
    //{ year: 2010, platform: "PS2", count: 38 },
    //{ year: 2010, platform: "PC", count: 90 },
    //{ year: 2008, platform: "PSP", count: 100 },
    //{ year: 1994, platform: "PS", count: 17 },
    //{ year: 1995, platform: "PC", count: 2 },
    //{ year: 2012, platform: "DS", count: 25 },
    //{ year: 2009, platform: "Wii", count: 325 },
    //{ year: 2014, platform: "WiiU", count: 31 },
    //{ year: 2006, platform: "PS3", count: 27 },
    //{ year: 1990, platform: "GB", count: 3 },
    //{ year: 2001, platform: "PS2", count: 185 },
    //{ year: 1988, platform: "GB", count: 1 },
    { year: 2006, platform: "PC", count: 52 },
  ],
};

const VerticalTemplateGroupedMode = (arg) => <BarD3 {...arg}></BarD3>;

export const VerticalChart_GroupedMode = VerticalTemplateGroupedMode.bind({});
VerticalChart_GroupedMode.args = {
  height: 700,
  width: 1000,
  labelFontSize: 20,
  yAxisFontSize: 14,
  xAxisFontSize: 14,
  xLimitLine: 100,
  paddingRight: 40,
  paddingLeft: 40,
  paddingTop: 0,
  paddingBottom: 40,
  legendX: 600,
  legendY: 5,
  labelPosition: "end",
  paddingInfoLabel: 10,
  visualMode: "vertical",
  cols: ["year", "platform"],
  metrics: ["count"],
  data: [
    { year: 2011, platform: "PC", count: 140 },
    { year: 2008, platform: "PC", count: 76 },
    { year: 1992, platform: "NES", count: 3 },
    { year: 1993, platform: "SCD", count: 1 },
    { year: 2006, platform: "PS2", count: 259 },
    { year: 2014, platform: "PSP", count: 10 },
    { year: 2011, platform: "PS2", count: 7 },
    { year: 2006, platform: "X360", count: 93 },
    { year: 2014, platform: "Wii", count: 6 },
    { year: 2008, platform: "Wii", count: 282 },
    { year: 2006, platform: "DS", count: 202 },
    { year: 2011, platform: "DS", count: 153 },
    { year: 2006, platform: "PSP", count: 190 },
    { year: 2006, platform: "PC", count: 52 },
  ],
};

const TemplateDoubleGroupedMode = (arg) => <BarD3 {...arg}></BarD3>;

export const HorizontalChart_DoubleGroupedMode = TemplateDoubleGroupedMode.bind(
  {}
);
HorizontalChart_DoubleGroupedMode.args = {
  height: 700,
  width: 1000,
  labelFontSize: 8,
  yAxisFontSize: 8,
  xAxisFontSize: 8,
  xLimitLine: 10,
  paddingRight: 40,
  paddingLeft: 40,
  paddingTop: 0,
  paddingBottom: 40,
  legendX: 600,
  legendY: 5,
  labelPosition: "end",
  paddingInfoLabel: 10,
  visualMode: "horizontal",
  cols: ["year", "platform", "publisher"],
  metrics: ["count"],
  data: [
    { year: 1996, platform: "N64", publisher: "GT Interactive", count: 2 },
    { year: 1995, platform: "PS", publisher: "Jaleco", count: 1 },
    { year: 1998, platform: "PC", publisher: "Electronic Arts", count: 1 },
    { year: 1996, platform: "SAT", publisher: "Micro Cabin", count: 1 },
    { year: 1998, platform: "GB", publisher: "Nintendo", count: 5 },
    { year: 1997, platform: "N64", publisher: "Natsume", count: 1 },
    { year: 1997, platform: "PS", publisher: "CTO SpA", count: 1 },
    { year: 1998, platform: "SAT", publisher: "NCS", count: 1 },
    { year: 1998, platform: "PS", publisher: "Sunsoft", count: 1 },
    { year: 1995, platform: "SAT", publisher: "Victor Interactive", count: 1 },
    { year: 1996, platform: "PS", publisher: "ASCII Entertainment", count: 1 },
    { year: 1996, platform: "PS", publisher: "Eidos Interactive", count: 3 },
    { year: 1996, platform: "PS", publisher: "Empire Interactive", count: 1 },
    {
      year: 1998,
      platform: "PS",
      publisher: "DreamWorks Interactive",
      count: 1,
    },
    { year: 1998, platform: "N64", publisher: "Fox Interactive", count: 1 },
    { year: 1996, platform: "PS", publisher: "ArtDink", count: 2 },
    { year: 1998, platform: "PS", publisher: "NewKidCo", count: 2 },
    { year: 1998, platform: "PS", publisher: "989 Studios", count: 6 },
    {
      year: 1997,
      platform: "PS",
      publisher: "Acclaim Entertainment",
      count: 5,
    },
    { year: 1998, platform: "GB", publisher: "Eidos Interactive", count: 1 },
    { year: 1995, platform: "SNES", publisher: "Pow", count: 1 },
    { year: 1998, platform: "PC", publisher: "Activision", count: 1 },
    { year: 1995, platform: "SAT", publisher: "Shogakukan", count: 2 },
    { year: 1997, platform: "N64", publisher: "Ocean", count: 2 },
    { year: 1998, platform: "PS", publisher: "Take-Two Interactive", count: 6 },
    { year: 1996, platform: "GB", publisher: "Nintendo", count: 4 },
    { year: 1995, platform: "SAT", publisher: "Atlus", count: 3 },
    {
      year: 1998,
      platform: "PS",
      publisher: "Acclaim Entertainment",
      count: 12,
    },
    { year: 1997, platform: "PS", publisher: "Electronic Arts", count: 21 },
    {
      year: 1995,
      platform: "SNES",
      publisher: "ASCII Entertainment",
      count: 2,
    },
    { year: 1995, platform: "SAT", publisher: "Glams", count: 1 },
    { year: 1996, platform: "PS", publisher: "From Software", count: 1 },
    {
      year: 1997,
      platform: "PS",
      publisher: "Midas Interactive Entertainment",
      count: 1,
    },
    { year: 1997, platform: "PS", publisher: "Virgin Interactive", count: 9 },
    {
      year: 1998,
      platform: "N64",
      publisher: "Gremlin Interactive Ltd",
      count: 1,
    },
    { year: 1997, platform: "PS", publisher: "Atlus", count: 1 },
    { year: 1995, platform: "SAT", publisher: "Tecmo Koei", count: 1 },
    { year: 1996, platform: "PS", publisher: "FunSoft", count: 1 },
    { year: 1996, platform: "PS", publisher: "Gust", count: 1 },
    { year: 1998, platform: "N64", publisher: "THQ", count: 3 },
    { year: 1995, platform: "SAT", publisher: "Jaleco", count: 1 },
    { year: 1996, platform: "PC", publisher: "Virgin Interactive", count: 1 },
    { year: 1996, platform: "PS", publisher: "Pioneer LDC", count: 2 },
    { year: 1995, platform: "PS", publisher: "Microprose", count: 1 },
    { year: 1998, platform: "PS", publisher: "Culture Publishers", count: 1 },
    { year: 1997, platform: "PS", publisher: "Ocean", count: 1 },
    {
      year: 1998,
      platform: "PS",
      publisher: "Gainax Network Systems",
      count: 2,
    },
    { year: 1998, platform: "N64", publisher: "Imagineer", count: 1 },
    { year: 1996, platform: "SNES", publisher: "Epoch", count: 1 },
    { year: 1997, platform: "PS", publisher: "Playmates", count: 1 },
  ],
};

const VerticalTemplateDoubleGroupedMode = (arg) => <BarD3 {...arg}></BarD3>;

export const VerticalChart_DoubleGroupedMode =
  VerticalTemplateDoubleGroupedMode.bind({});
VerticalChart_DoubleGroupedMode.args = {
  height: 700,
  width: 1000,
  labelFontSize: 8,
  yAxisFontSize: 8,
  xAxisFontSize: 8,
  xLimitLine: 10,
  paddingRight: 40,
  paddingLeft: 40,
  paddingTop: 0,
  paddingBottom: 40,
  legendX: 600,
  legendY: 5,
  labelPosition: "end",
  paddingInfoLabel: 10,
  visualMode: "vertical",
  cols: ["year", "platform", "publisher"],
  metrics: ["count"],
  data: [
    { year: 1996, platform: "N64", publisher: "GT Interactive", count: 2 },
    { year: 1995, platform: "PS", publisher: "Jaleco", count: 1 },
    { year: 1998, platform: "PC", publisher: "Electronic Arts", count: 1 },
    { year: 1996, platform: "SAT", publisher: "Micro Cabin", count: 1 },
    { year: 1998, platform: "GB", publisher: "Nintendo", count: 5 },
    { year: 1997, platform: "N64", publisher: "Natsume", count: 1 },
    { year: 1997, platform: "PS", publisher: "CTO SpA", count: 1 },
    { year: 1998, platform: "SAT", publisher: "NCS", count: 1 },
    { year: 1998, platform: "PS", publisher: "Sunsoft", count: 1 },
    { year: 1995, platform: "SAT", publisher: "Victor Interactive", count: 1 },
    { year: 1996, platform: "PS", publisher: "ASCII Entertainment", count: 1 },
    { year: 1996, platform: "PS", publisher: "Eidos Interactive", count: 3 },
    { year: 1996, platform: "PS", publisher: "Empire Interactive", count: 1 },
    {
      year: 1998,
      platform: "PS",
      publisher: "DreamWorks Interactive",
      count: 1,
    },
    { year: 1998, platform: "N64", publisher: "Fox Interactive", count: 1 },
    { year: 1996, platform: "PS", publisher: "ArtDink", count: 2 },
    { year: 1998, platform: "PS", publisher: "NewKidCo", count: 2 },
    { year: 1998, platform: "PS", publisher: "989 Studios", count: 6 },
    {
      year: 1997,
      platform: "PS",
      publisher: "Acclaim Entertainment",
      count: 5,
    },
    { year: 1998, platform: "GB", publisher: "Eidos Interactive", count: 1 },
    { year: 1995, platform: "SNES", publisher: "Pow", count: 1 },
    { year: 1998, platform: "PC", publisher: "Activision", count: 1 },
    { year: 1995, platform: "SAT", publisher: "Shogakukan", count: 2 },
    { year: 1997, platform: "N64", publisher: "Ocean", count: 2 },
    { year: 1998, platform: "PS", publisher: "Take-Two Interactive", count: 6 },
    { year: 1996, platform: "GB", publisher: "Nintendo", count: 4 },
    { year: 1995, platform: "SAT", publisher: "Atlus", count: 3 },
    {
      year: 1998,
      platform: "PS",
      publisher: "Acclaim Entertainment",
      count: 12,
    },
    { year: 1997, platform: "PS", publisher: "Electronic Arts", count: 21 },
    {
      year: 1995,
      platform: "SNES",
      publisher: "ASCII Entertainment",
      count: 2,
    },
    { year: 1995, platform: "SAT", publisher: "Glams", count: 1 },
    { year: 1996, platform: "PS", publisher: "From Software", count: 1 },
    {
      year: 1997,
      platform: "PS",
      publisher: "Midas Interactive Entertainment",
      count: 1,
    },
    { year: 1997, platform: "PS", publisher: "Virgin Interactive", count: 9 },
    {
      year: 1998,
      platform: "N64",
      publisher: "Gremlin Interactive Ltd",
      count: 1,
    },
    { year: 1997, platform: "PS", publisher: "Atlus", count: 1 },
    { year: 1995, platform: "SAT", publisher: "Tecmo Koei", count: 1 },
    { year: 1996, platform: "PS", publisher: "FunSoft", count: 1 },
    { year: 1996, platform: "PS", publisher: "Gust", count: 1 },
    { year: 1998, platform: "N64", publisher: "THQ", count: 3 },
    { year: 1995, platform: "SAT", publisher: "Jaleco", count: 1 },
    { year: 1996, platform: "PC", publisher: "Virgin Interactive", count: 1 },
    { year: 1996, platform: "PS", publisher: "Pioneer LDC", count: 2 },
    { year: 1995, platform: "PS", publisher: "Microprose", count: 1 },
    { year: 1998, platform: "PS", publisher: "Culture Publishers", count: 1 },
    { year: 1997, platform: "PS", publisher: "Ocean", count: 1 },
    {
      year: 1998,
      platform: "PS",
      publisher: "Gainax Network Systems",
      count: 2,
    },
    { year: 1998, platform: "N64", publisher: "Imagineer", count: 1 },
    { year: 1996, platform: "SNES", publisher: "Epoch", count: 1 },
    { year: 1997, platform: "PS", publisher: "Playmates", count: 1 },
  ],
};

const TemplateVertical = (arg) => <BarD3 {...arg}></BarD3>;

export const VerticalChart = TemplateVertical.bind({});
VerticalChart.args = {
  height: 700,
  width: 1000,
  labelFontSize: 20,
  yAxisFontSize: 14,
  xAxisFontSize: 14,
  xLimitLine: 100,
  paddingRight: 40,
  paddingLeft: 40,
  paddingTop: 0,
  paddingBottom: 40,
  legendX: 600,
  legendY: 5,
  labelPosition: "end",
  paddingInfoLabel: 10,
  visualMode: "vertical",
  cols: ["platform"],
  metrics: ["count"],
  data: [
    { platform: "TG16", count: 2 },
    { platform: "PSP", count: 1213 },
    { platform: "2600", count: 133 },
    { platform: "PS4", count: 336 },
    { platform: "N64", count: 319 },
    { platform: "GBA", count: 822 },
    { platform: "GG", count: 1 },
    { platform: "PSV", count: 411 },
    { platform: "XB", count: 824 },
    { platform: "DC", count: 52 },
    { platform: "XOne", count: 213 },
    { platform: "PS2", count: 2161 },
    { platform: "Wii", count: 1325 },
    { platform: "X360", count: 1265 },
    { platform: "WiiU", count: 143 },
    { platform: "PC", count: 960 },
    { platform: "DS", count: 2162 },
    { platform: "WS", count: 6 },
    { platform: "PCFX", count: 1 },
    { platform: "PS3", count: 1329 },
    { platform: "GEN", count: 27 },
    { platform: "SNES", count: 239 },
    { platform: "NG", count: 12 },
    { platform: "GB", count: 98 },
    { platform: "PS", count: 1196 },
    { platform: "SCD", count: 6 },
    { platform: "3DS", count: 509 },
    { platform: "3DO", count: 3 },
    { platform: "NES", count: 98 },
    { platform: "SAT", count: 173 },
    { platform: "GC", count: 556 },
  ],
};
